language: c
script:
  - ./bootstrap
  - ./configure --with-gmetad --with-perl=/usr --enable-status --with-memcached
  - make all
before_script:
  - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ saucy main universe"
  - sudo apt-get update
  - sudo apt-get -o Dpkg::Options::="--force-overwrite" -y install libapr1-dev libaprutil1-dev libconfuse-dev libexpat1-dev libpcre3-dev libssl-dev librrd-dev libperl-dev libmemcached-dev libtool m4 gperf zlib1g-dev pkg-config
  - sudo add-apt-repository -y "deb http://http.debian.net/debian/ sid main"
  - sudo apt-get update -qq
  - sudo apt-get install -qq --force-yes libck-dev
